/*
 * This file is generated by jOOQ.
*/
package ru.grsp.backend.model_jooq.tables.records;


import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>ocstore</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<OcOrderRecord, Integer> IDENTITY_OC_ORDER = Identities0.IDENTITY_OC_ORDER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<OcOrderRecord> KEY_OC_ORDER_PRIMARY = UniqueKeys0.KEY_OC_ORDER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<OcOrderRecord, Integer> IDENTITY_OC_ORDER = Internal.createIdentity(OcOrder.OC_ORDER, OcOrder.OC_ORDER.ORDER_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<OcOrderRecord> KEY_OC_ORDER_PRIMARY = Internal.createUniqueKey(OcOrder.OC_ORDER, "KEY_oc_order_PRIMARY", OcOrder.OC_ORDER.ORDER_ID);
    }
}
