/*
 * This file is generated by jOOQ.
*/
package ru.grsp.backend.model_jooq.tables.records;


import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OcOrder extends TableImpl<OcOrderRecord> {

    private static final long serialVersionUID = -1558162244;

    /**
     * The reference instance of <code>ocstore.oc_order</code>
     */
    public static final OcOrder OC_ORDER = new OcOrder();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OcOrderRecord> getRecordType() {
        return OcOrderRecord.class;
    }

    /**
     * The column <code>ocstore.oc_order.order_id</code>.
     */
    public final TableField<OcOrderRecord, Integer> ORDER_ID = createField("order_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>ocstore.oc_order.invoice_no</code>.
     */
    public final TableField<OcOrderRecord, Integer> INVOICE_NO = createField("invoice_no", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ocstore.oc_order.invoice_prefix</code>.
     */
    public final TableField<OcOrderRecord, String> INVOICE_PREFIX = createField("invoice_prefix", org.jooq.impl.SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.store_id</code>.
     */
    public final TableField<OcOrderRecord, Integer> STORE_ID = createField("store_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ocstore.oc_order.store_name</code>.
     */
    public final TableField<OcOrderRecord, String> STORE_NAME = createField("store_name", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.store_url</code>.
     */
    public final TableField<OcOrderRecord, String> STORE_URL = createField("store_url", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.customer_id</code>.
     */
    public final TableField<OcOrderRecord, Integer> CUSTOMER_ID = createField("customer_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ocstore.oc_order.customer_group_id</code>.
     */
    public final TableField<OcOrderRecord, Integer> CUSTOMER_GROUP_ID = createField("customer_group_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ocstore.oc_order.firstname</code>.
     */
    public final TableField<OcOrderRecord, String> FIRSTNAME = createField("firstname", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.lastname</code>.
     */
    public final TableField<OcOrderRecord, String> LASTNAME = createField("lastname", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.email</code>.
     */
    public final TableField<OcOrderRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR(96).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.telephone</code>.
     */
    public final TableField<OcOrderRecord, String> TELEPHONE = createField("telephone", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.fax</code>.
     */
    public final TableField<OcOrderRecord, String> FAX = createField("fax", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.custom_field</code>.
     */
    public final TableField<OcOrderRecord, String> CUSTOM_FIELD = createField("custom_field", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.payment_firstname</code>.
     */
    public final TableField<OcOrderRecord, String> PAYMENT_FIRSTNAME = createField("payment_firstname", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.payment_lastname</code>.
     */
    public final TableField<OcOrderRecord, String> PAYMENT_LASTNAME = createField("payment_lastname", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.payment_company</code>.
     */
    public final TableField<OcOrderRecord, String> PAYMENT_COMPANY = createField("payment_company", org.jooq.impl.SQLDataType.VARCHAR(60).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.payment_address_1</code>.
     */
    public final TableField<OcOrderRecord, String> PAYMENT_ADDRESS_1 = createField("payment_address_1", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.payment_address_2</code>.
     */
    public final TableField<OcOrderRecord, String> PAYMENT_ADDRESS_2 = createField("payment_address_2", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.payment_city</code>.
     */
    public final TableField<OcOrderRecord, String> PAYMENT_CITY = createField("payment_city", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.payment_postcode</code>.
     */
    public final TableField<OcOrderRecord, String> PAYMENT_POSTCODE = createField("payment_postcode", org.jooq.impl.SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.payment_country</code>.
     */
    public final TableField<OcOrderRecord, String> PAYMENT_COUNTRY = createField("payment_country", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.payment_country_id</code>.
     */
    public final TableField<OcOrderRecord, Integer> PAYMENT_COUNTRY_ID = createField("payment_country_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.payment_zone</code>.
     */
    public final TableField<OcOrderRecord, String> PAYMENT_ZONE = createField("payment_zone", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.payment_zone_id</code>.
     */
    public final TableField<OcOrderRecord, Integer> PAYMENT_ZONE_ID = createField("payment_zone_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.payment_address_format</code>.
     */
    public final TableField<OcOrderRecord, String> PAYMENT_ADDRESS_FORMAT = createField("payment_address_format", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.payment_custom_field</code>.
     */
    public final TableField<OcOrderRecord, String> PAYMENT_CUSTOM_FIELD = createField("payment_custom_field", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.payment_method</code>.
     */
    public final TableField<OcOrderRecord, String> PAYMENT_METHOD = createField("payment_method", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.payment_code</code>.
     */
    public final TableField<OcOrderRecord, String> PAYMENT_CODE = createField("payment_code", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.shipping_firstname</code>.
     */
    public final TableField<OcOrderRecord, String> SHIPPING_FIRSTNAME = createField("shipping_firstname", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.shipping_lastname</code>.
     */
    public final TableField<OcOrderRecord, String> SHIPPING_LASTNAME = createField("shipping_lastname", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.shipping_company</code>.
     */
    public final TableField<OcOrderRecord, String> SHIPPING_COMPANY = createField("shipping_company", org.jooq.impl.SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.shipping_address_1</code>.
     */
    public final TableField<OcOrderRecord, String> SHIPPING_ADDRESS_1 = createField("shipping_address_1", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.shipping_address_2</code>.
     */
    public final TableField<OcOrderRecord, String> SHIPPING_ADDRESS_2 = createField("shipping_address_2", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.shipping_city</code>.
     */
    public final TableField<OcOrderRecord, String> SHIPPING_CITY = createField("shipping_city", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.shipping_postcode</code>.
     */
    public final TableField<OcOrderRecord, String> SHIPPING_POSTCODE = createField("shipping_postcode", org.jooq.impl.SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.shipping_country</code>.
     */
    public final TableField<OcOrderRecord, String> SHIPPING_COUNTRY = createField("shipping_country", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.shipping_country_id</code>.
     */
    public final TableField<OcOrderRecord, Integer> SHIPPING_COUNTRY_ID = createField("shipping_country_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.shipping_zone</code>.
     */
    public final TableField<OcOrderRecord, String> SHIPPING_ZONE = createField("shipping_zone", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.shipping_zone_id</code>.
     */
    public final TableField<OcOrderRecord, Integer> SHIPPING_ZONE_ID = createField("shipping_zone_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.shipping_address_format</code>.
     */
    public final TableField<OcOrderRecord, String> SHIPPING_ADDRESS_FORMAT = createField("shipping_address_format", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.shipping_custom_field</code>.
     */
    public final TableField<OcOrderRecord, String> SHIPPING_CUSTOM_FIELD = createField("shipping_custom_field", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.shipping_method</code>.
     */
    public final TableField<OcOrderRecord, String> SHIPPING_METHOD = createField("shipping_method", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.shipping_code</code>.
     */
    public final TableField<OcOrderRecord, String> SHIPPING_CODE = createField("shipping_code", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.comment</code>.
     */
    public final TableField<OcOrderRecord, String> COMMENT = createField("comment", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.total</code>.
     */
    public final TableField<OcOrderRecord, BigDecimal> TOTAL = createField("total", org.jooq.impl.SQLDataType.DECIMAL(15, 4).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.0000", org.jooq.impl.SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>ocstore.oc_order.order_status_id</code>.
     */
    public final TableField<OcOrderRecord, Integer> ORDER_STATUS_ID = createField("order_status_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ocstore.oc_order.affiliate_id</code>.
     */
    public final TableField<OcOrderRecord, Integer> AFFILIATE_ID = createField("affiliate_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.commission</code>.
     */
    public final TableField<OcOrderRecord, BigDecimal> COMMISSION = createField("commission", org.jooq.impl.SQLDataType.DECIMAL(15, 4).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.marketing_id</code>.
     */
    public final TableField<OcOrderRecord, Integer> MARKETING_ID = createField("marketing_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.tracking</code>.
     */
    public final TableField<OcOrderRecord, String> TRACKING = createField("tracking", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.language_id</code>.
     */
    public final TableField<OcOrderRecord, Integer> LANGUAGE_ID = createField("language_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.currency_id</code>.
     */
    public final TableField<OcOrderRecord, Integer> CURRENCY_ID = createField("currency_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.currency_code</code>.
     */
    public final TableField<OcOrderRecord, String> CURRENCY_CODE = createField("currency_code", org.jooq.impl.SQLDataType.VARCHAR(3).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.currency_value</code>.
     */
    public final TableField<OcOrderRecord, BigDecimal> CURRENCY_VALUE = createField("currency_value", org.jooq.impl.SQLDataType.DECIMAL(15, 8).nullable(false).defaultValue(org.jooq.impl.DSL.inline("1.00000000", org.jooq.impl.SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>ocstore.oc_order.ip</code>.
     */
    public final TableField<OcOrderRecord, String> IP = createField("ip", org.jooq.impl.SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.forwarded_ip</code>.
     */
    public final TableField<OcOrderRecord, String> FORWARDED_IP = createField("forwarded_ip", org.jooq.impl.SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.user_agent</code>.
     */
    public final TableField<OcOrderRecord, String> USER_AGENT = createField("user_agent", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.accept_language</code>.
     */
    public final TableField<OcOrderRecord, String> ACCEPT_LANGUAGE = createField("accept_language", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.date_added</code>.
     */
    public final TableField<OcOrderRecord, Timestamp> DATE_ADDED = createField("date_added", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>ocstore.oc_order.date_modified</code>.
     */
    public final TableField<OcOrderRecord, Timestamp> DATE_MODIFIED = createField("date_modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>ocstore.oc_order</code> table reference
     */
    public OcOrder() {
        this(DSL.name("oc_order"), null);
    }

    /**
     * Create an aliased <code>ocstore.oc_order</code> table reference
     */
    public OcOrder(String alias) {
        this(DSL.name(alias), OC_ORDER);
    }

    /**
     * Create an aliased <code>ocstore.oc_order</code> table reference
     */
    public OcOrder(Name alias) {
        this(alias, OC_ORDER);
    }

    private OcOrder(Name alias, Table<OcOrderRecord> aliased) {
        this(alias, aliased, null);
    }

    private OcOrder(Name alias, Table<OcOrderRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ocstore.OCSTORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.OC_ORDER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<OcOrderRecord, Integer> getIdentity() {
        return Keys.IDENTITY_OC_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OcOrderRecord> getPrimaryKey() {
        return Keys.KEY_OC_ORDER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OcOrderRecord>> getKeys() {
        return Arrays.<UniqueKey<OcOrderRecord>>asList(Keys.KEY_OC_ORDER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OcOrder as(String alias) {
        return new OcOrder(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OcOrder as(Name alias) {
        return new OcOrder(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OcOrder rename(String name) {
        return new OcOrder(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OcOrder rename(Name name) {
        return new OcOrder(name, null);
    }
}
