/*
 * This file is generated by jOOQ.
*/
package ru.grsp.backend.model_jooq.tables.records;


import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OcOrderRecord extends UpdatableRecordImpl<OcOrderRecord> {

    private static final long serialVersionUID = 24576499;

    /**
     * Setter for <code>ocstore.oc_order.order_id</code>.
     */
    public void setOrderId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.order_id</code>.
     */
    public Integer getOrderId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ocstore.oc_order.invoice_no</code>.
     */
    public void setInvoiceNo(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.invoice_no</code>.
     */
    public Integer getInvoiceNo() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>ocstore.oc_order.invoice_prefix</code>.
     */
    public void setInvoicePrefix(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.invoice_prefix</code>.
     */
    public String getInvoicePrefix() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ocstore.oc_order.store_id</code>.
     */
    public void setStoreId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.store_id</code>.
     */
    public Integer getStoreId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>ocstore.oc_order.store_name</code>.
     */
    public void setStoreName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.store_name</code>.
     */
    public String getStoreName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ocstore.oc_order.store_url</code>.
     */
    public void setStoreUrl(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.store_url</code>.
     */
    public String getStoreUrl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ocstore.oc_order.customer_id</code>.
     */
    public void setCustomerId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.customer_id</code>.
     */
    public Integer getCustomerId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>ocstore.oc_order.customer_group_id</code>.
     */
    public void setCustomerGroupId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.customer_group_id</code>.
     */
    public Integer getCustomerGroupId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>ocstore.oc_order.firstname</code>.
     */
    public void setFirstname(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.firstname</code>.
     */
    public String getFirstname() {
        return (String) get(8);
    }

    /**
     * Setter for <code>ocstore.oc_order.lastname</code>.
     */
    public void setLastname(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.lastname</code>.
     */
    public String getLastname() {
        return (String) get(9);
    }

    /**
     * Setter for <code>ocstore.oc_order.email</code>.
     */
    public void setEmail(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.email</code>.
     */
    public String getEmail() {
        return (String) get(10);
    }

    /**
     * Setter for <code>ocstore.oc_order.telephone</code>.
     */
    public void setTelephone(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.telephone</code>.
     */
    public String getTelephone() {
        return (String) get(11);
    }

    /**
     * Setter for <code>ocstore.oc_order.fax</code>.
     */
    public void setFax(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.fax</code>.
     */
    public String getFax() {
        return (String) get(12);
    }

    /**
     * Setter for <code>ocstore.oc_order.custom_field</code>.
     */
    public void setCustomField(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.custom_field</code>.
     */
    public String getCustomField() {
        return (String) get(13);
    }

    /**
     * Setter for <code>ocstore.oc_order.payment_firstname</code>.
     */
    public void setPaymentFirstname(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.payment_firstname</code>.
     */
    public String getPaymentFirstname() {
        return (String) get(14);
    }

    /**
     * Setter for <code>ocstore.oc_order.payment_lastname</code>.
     */
    public void setPaymentLastname(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.payment_lastname</code>.
     */
    public String getPaymentLastname() {
        return (String) get(15);
    }

    /**
     * Setter for <code>ocstore.oc_order.payment_company</code>.
     */
    public void setPaymentCompany(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.payment_company</code>.
     */
    public String getPaymentCompany() {
        return (String) get(16);
    }

    /**
     * Setter for <code>ocstore.oc_order.payment_address_1</code>.
     */
    public void setPaymentAddress_1(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.payment_address_1</code>.
     */
    public String getPaymentAddress_1() {
        return (String) get(17);
    }

    /**
     * Setter for <code>ocstore.oc_order.payment_address_2</code>.
     */
    public void setPaymentAddress_2(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.payment_address_2</code>.
     */
    public String getPaymentAddress_2() {
        return (String) get(18);
    }

    /**
     * Setter for <code>ocstore.oc_order.payment_city</code>.
     */
    public void setPaymentCity(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.payment_city</code>.
     */
    public String getPaymentCity() {
        return (String) get(19);
    }

    /**
     * Setter for <code>ocstore.oc_order.payment_postcode</code>.
     */
    public void setPaymentPostcode(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.payment_postcode</code>.
     */
    public String getPaymentPostcode() {
        return (String) get(20);
    }

    /**
     * Setter for <code>ocstore.oc_order.payment_country</code>.
     */
    public void setPaymentCountry(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.payment_country</code>.
     */
    public String getPaymentCountry() {
        return (String) get(21);
    }

    /**
     * Setter for <code>ocstore.oc_order.payment_country_id</code>.
     */
    public void setPaymentCountryId(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.payment_country_id</code>.
     */
    public Integer getPaymentCountryId() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>ocstore.oc_order.payment_zone</code>.
     */
    public void setPaymentZone(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.payment_zone</code>.
     */
    public String getPaymentZone() {
        return (String) get(23);
    }

    /**
     * Setter for <code>ocstore.oc_order.payment_zone_id</code>.
     */
    public void setPaymentZoneId(Integer value) {
        set(24, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.payment_zone_id</code>.
     */
    public Integer getPaymentZoneId() {
        return (Integer) get(24);
    }

    /**
     * Setter for <code>ocstore.oc_order.payment_address_format</code>.
     */
    public void setPaymentAddressFormat(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.payment_address_format</code>.
     */
    public String getPaymentAddressFormat() {
        return (String) get(25);
    }

    /**
     * Setter for <code>ocstore.oc_order.payment_custom_field</code>.
     */
    public void setPaymentCustomField(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.payment_custom_field</code>.
     */
    public String getPaymentCustomField() {
        return (String) get(26);
    }

    /**
     * Setter for <code>ocstore.oc_order.payment_method</code>.
     */
    public void setPaymentMethod(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.payment_method</code>.
     */
    public String getPaymentMethod() {
        return (String) get(27);
    }

    /**
     * Setter for <code>ocstore.oc_order.payment_code</code>.
     */
    public void setPaymentCode(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.payment_code</code>.
     */
    public String getPaymentCode() {
        return (String) get(28);
    }

    /**
     * Setter for <code>ocstore.oc_order.shipping_firstname</code>.
     */
    public void setShippingFirstname(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.shipping_firstname</code>.
     */
    public String getShippingFirstname() {
        return (String) get(29);
    }

    /**
     * Setter for <code>ocstore.oc_order.shipping_lastname</code>.
     */
    public void setShippingLastname(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.shipping_lastname</code>.
     */
    public String getShippingLastname() {
        return (String) get(30);
    }

    /**
     * Setter for <code>ocstore.oc_order.shipping_company</code>.
     */
    public void setShippingCompany(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.shipping_company</code>.
     */
    public String getShippingCompany() {
        return (String) get(31);
    }

    /**
     * Setter for <code>ocstore.oc_order.shipping_address_1</code>.
     */
    public void setShippingAddress_1(String value) {
        set(32, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.shipping_address_1</code>.
     */
    public String getShippingAddress_1() {
        return (String) get(32);
    }

    /**
     * Setter for <code>ocstore.oc_order.shipping_address_2</code>.
     */
    public void setShippingAddress_2(String value) {
        set(33, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.shipping_address_2</code>.
     */
    public String getShippingAddress_2() {
        return (String) get(33);
    }

    /**
     * Setter for <code>ocstore.oc_order.shipping_city</code>.
     */
    public void setShippingCity(String value) {
        set(34, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.shipping_city</code>.
     */
    public String getShippingCity() {
        return (String) get(34);
    }

    /**
     * Setter for <code>ocstore.oc_order.shipping_postcode</code>.
     */
    public void setShippingPostcode(String value) {
        set(35, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.shipping_postcode</code>.
     */
    public String getShippingPostcode() {
        return (String) get(35);
    }

    /**
     * Setter for <code>ocstore.oc_order.shipping_country</code>.
     */
    public void setShippingCountry(String value) {
        set(36, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.shipping_country</code>.
     */
    public String getShippingCountry() {
        return (String) get(36);
    }

    /**
     * Setter for <code>ocstore.oc_order.shipping_country_id</code>.
     */
    public void setShippingCountryId(Integer value) {
        set(37, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.shipping_country_id</code>.
     */
    public Integer getShippingCountryId() {
        return (Integer) get(37);
    }

    /**
     * Setter for <code>ocstore.oc_order.shipping_zone</code>.
     */
    public void setShippingZone(String value) {
        set(38, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.shipping_zone</code>.
     */
    public String getShippingZone() {
        return (String) get(38);
    }

    /**
     * Setter for <code>ocstore.oc_order.shipping_zone_id</code>.
     */
    public void setShippingZoneId(Integer value) {
        set(39, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.shipping_zone_id</code>.
     */
    public Integer getShippingZoneId() {
        return (Integer) get(39);
    }

    /**
     * Setter for <code>ocstore.oc_order.shipping_address_format</code>.
     */
    public void setShippingAddressFormat(String value) {
        set(40, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.shipping_address_format</code>.
     */
    public String getShippingAddressFormat() {
        return (String) get(40);
    }

    /**
     * Setter for <code>ocstore.oc_order.shipping_custom_field</code>.
     */
    public void setShippingCustomField(String value) {
        set(41, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.shipping_custom_field</code>.
     */
    public String getShippingCustomField() {
        return (String) get(41);
    }

    /**
     * Setter for <code>ocstore.oc_order.shipping_method</code>.
     */
    public void setShippingMethod(String value) {
        set(42, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.shipping_method</code>.
     */
    public String getShippingMethod() {
        return (String) get(42);
    }

    /**
     * Setter for <code>ocstore.oc_order.shipping_code</code>.
     */
    public void setShippingCode(String value) {
        set(43, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.shipping_code</code>.
     */
    public String getShippingCode() {
        return (String) get(43);
    }

    /**
     * Setter for <code>ocstore.oc_order.comment</code>.
     */
    public void setComment(String value) {
        set(44, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.comment</code>.
     */
    public String getComment() {
        return (String) get(44);
    }

    /**
     * Setter for <code>ocstore.oc_order.total</code>.
     */
    public void setTotal(BigDecimal value) {
        set(45, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.total</code>.
     */
    public BigDecimal getTotal() {
        return (BigDecimal) get(45);
    }

    /**
     * Setter for <code>ocstore.oc_order.order_status_id</code>.
     */
    public void setOrderStatusId(Integer value) {
        set(46, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.order_status_id</code>.
     */
    public Integer getOrderStatusId() {
        return (Integer) get(46);
    }

    /**
     * Setter for <code>ocstore.oc_order.affiliate_id</code>.
     */
    public void setAffiliateId(Integer value) {
        set(47, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.affiliate_id</code>.
     */
    public Integer getAffiliateId() {
        return (Integer) get(47);
    }

    /**
     * Setter for <code>ocstore.oc_order.commission</code>.
     */
    public void setCommission(BigDecimal value) {
        set(48, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.commission</code>.
     */
    public BigDecimal getCommission() {
        return (BigDecimal) get(48);
    }

    /**
     * Setter for <code>ocstore.oc_order.marketing_id</code>.
     */
    public void setMarketingId(Integer value) {
        set(49, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.marketing_id</code>.
     */
    public Integer getMarketingId() {
        return (Integer) get(49);
    }

    /**
     * Setter for <code>ocstore.oc_order.tracking</code>.
     */
    public void setTracking(String value) {
        set(50, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.tracking</code>.
     */
    public String getTracking() {
        return (String) get(50);
    }

    /**
     * Setter for <code>ocstore.oc_order.language_id</code>.
     */
    public void setLanguageId(Integer value) {
        set(51, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.language_id</code>.
     */
    public Integer getLanguageId() {
        return (Integer) get(51);
    }

    /**
     * Setter for <code>ocstore.oc_order.currency_id</code>.
     */
    public void setCurrencyId(Integer value) {
        set(52, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.currency_id</code>.
     */
    public Integer getCurrencyId() {
        return (Integer) get(52);
    }

    /**
     * Setter for <code>ocstore.oc_order.currency_code</code>.
     */
    public void setCurrencyCode(String value) {
        set(53, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.currency_code</code>.
     */
    public String getCurrencyCode() {
        return (String) get(53);
    }

    /**
     * Setter for <code>ocstore.oc_order.currency_value</code>.
     */
    public void setCurrencyValue(BigDecimal value) {
        set(54, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.currency_value</code>.
     */
    public BigDecimal getCurrencyValue() {
        return (BigDecimal) get(54);
    }

    /**
     * Setter for <code>ocstore.oc_order.ip</code>.
     */
    public void setIp(String value) {
        set(55, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.ip</code>.
     */
    public String getIp() {
        return (String) get(55);
    }

    /**
     * Setter for <code>ocstore.oc_order.forwarded_ip</code>.
     */
    public void setForwardedIp(String value) {
        set(56, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.forwarded_ip</code>.
     */
    public String getForwardedIp() {
        return (String) get(56);
    }

    /**
     * Setter for <code>ocstore.oc_order.user_agent</code>.
     */
    public void setUserAgent(String value) {
        set(57, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.user_agent</code>.
     */
    public String getUserAgent() {
        return (String) get(57);
    }

    /**
     * Setter for <code>ocstore.oc_order.accept_language</code>.
     */
    public void setAcceptLanguage(String value) {
        set(58, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.accept_language</code>.
     */
    public String getAcceptLanguage() {
        return (String) get(58);
    }

    /**
     * Setter for <code>ocstore.oc_order.date_added</code>.
     */
    public void setDateAdded(Timestamp value) {
        set(59, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.date_added</code>.
     */
    public Timestamp getDateAdded() {
        return (Timestamp) get(59);
    }

    /**
     * Setter for <code>ocstore.oc_order.date_modified</code>.
     */
    public void setDateModified(Timestamp value) {
        set(60, value);
    }

    /**
     * Getter for <code>ocstore.oc_order.date_modified</code>.
     */
    public Timestamp getDateModified() {
        return (Timestamp) get(60);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OcOrderRecord
     */
    public OcOrderRecord() {
        super(OcOrder.OC_ORDER);
    }

    /**
     * Create a detached, initialised OcOrderRecord
     */
    public OcOrderRecord(Integer orderId, Integer invoiceNo, String invoicePrefix, Integer storeId, String storeName, String storeUrl, Integer customerId, Integer customerGroupId, String firstname, String lastname, String email, String telephone, String fax, String customField, String paymentFirstname, String paymentLastname, String paymentCompany, String paymentAddress_1, String paymentAddress_2, String paymentCity, String paymentPostcode, String paymentCountry, Integer paymentCountryId, String paymentZone, Integer paymentZoneId, String paymentAddressFormat, String paymentCustomField, String paymentMethod, String paymentCode, String shippingFirstname, String shippingLastname, String shippingCompany, String shippingAddress_1, String shippingAddress_2, String shippingCity, String shippingPostcode, String shippingCountry, Integer shippingCountryId, String shippingZone, Integer shippingZoneId, String shippingAddressFormat, String shippingCustomField, String shippingMethod, String shippingCode, String comment, BigDecimal total, Integer orderStatusId, Integer affiliateId, BigDecimal commission, Integer marketingId, String tracking, Integer languageId, Integer currencyId, String currencyCode, BigDecimal currencyValue, String ip, String forwardedIp, String userAgent, String acceptLanguage, Timestamp dateAdded, Timestamp dateModified) {
        super(OcOrder.OC_ORDER);

        set(0, orderId);
        set(1, invoiceNo);
        set(2, invoicePrefix);
        set(3, storeId);
        set(4, storeName);
        set(5, storeUrl);
        set(6, customerId);
        set(7, customerGroupId);
        set(8, firstname);
        set(9, lastname);
        set(10, email);
        set(11, telephone);
        set(12, fax);
        set(13, customField);
        set(14, paymentFirstname);
        set(15, paymentLastname);
        set(16, paymentCompany);
        set(17, paymentAddress_1);
        set(18, paymentAddress_2);
        set(19, paymentCity);
        set(20, paymentPostcode);
        set(21, paymentCountry);
        set(22, paymentCountryId);
        set(23, paymentZone);
        set(24, paymentZoneId);
        set(25, paymentAddressFormat);
        set(26, paymentCustomField);
        set(27, paymentMethod);
        set(28, paymentCode);
        set(29, shippingFirstname);
        set(30, shippingLastname);
        set(31, shippingCompany);
        set(32, shippingAddress_1);
        set(33, shippingAddress_2);
        set(34, shippingCity);
        set(35, shippingPostcode);
        set(36, shippingCountry);
        set(37, shippingCountryId);
        set(38, shippingZone);
        set(39, shippingZoneId);
        set(40, shippingAddressFormat);
        set(41, shippingCustomField);
        set(42, shippingMethod);
        set(43, shippingCode);
        set(44, comment);
        set(45, total);
        set(46, orderStatusId);
        set(47, affiliateId);
        set(48, commission);
        set(49, marketingId);
        set(50, tracking);
        set(51, languageId);
        set(52, currencyId);
        set(53, currencyCode);
        set(54, currencyValue);
        set(55, ip);
        set(56, forwardedIp);
        set(57, userAgent);
        set(58, acceptLanguage);
        set(59, dateAdded);
        set(60, dateModified);
    }
}
