/*
 * This file is generated by jOOQ.
*/
package ru.grsp.backend.model_jooq.tables.records;


import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ocstore extends SchemaImpl {

    private static final long serialVersionUID = -902147427;

    /**
     * The reference instance of <code>ocstore</code>
     */
    public static final Ocstore OCSTORE = new Ocstore();

    /**
     * The table <code>ocstore.oc_order</code>.
     */
    public final OcOrder OC_ORDER = OcOrder.OC_ORDER;

    /**
     * No further instances allowed
     */
    private Ocstore() {
        super("ocstore", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            OcOrder.OC_ORDER);
    }
}
