/*
 * This file is generated by jOOQ.
*/
package ru.grsp.backend.model_jooq.tables.records;


import javax.annotation.Generated;


/**
 * Convenience access to all tables in ocstore
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ocstore.oc_order</code>.
     */
    public static final OcOrder OC_ORDER = OcOrder.OC_ORDER;
}
