tracer.property: "I AM THE DEFAULT"
spring:
  kafka:
    bootstrap-servers: localhost:9092
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
  datasource:
    url: jdbc:mysql://localhost:3306/ocstore
    username: store-connector
    password: psswd
    testWhileIdle: true
    validationQuery: SELECT 1